import json
import os

locales = {
    "en": {
        "common.confirm": "Confirm",
        "common.cancel": "Cancel",
        "common.back": "Back",
        "common.continue": "Continue",
        "common.close": "Close",
        "common.save": "Save",
        "common.loading": "Loading...",
        "common.skip": "Skip",
        "common.next": "Next",
        "common.finish": "Finish",
        "common.level": "Level",
        "common.week": "Week",
        "common.season": "Season",
        "common.currency": "£",

        "nav.hub": "Career Hub",
        "nav.overview": "Overview",
        "nav.match": "Play Match",
        "nav.training": "Training",
        "nav.rest": "Rest & Recover",
        "nav.shop": "Lifestyle Shop",
        "nav.social": "Social Activities",
        "nav.events": "Life Events",
        "nav.phone": "Smartphone",
        "nav.transfers": "Transfer Market",
        "nav.sponsorship": "Sponsorships",
        "nav.legacy": "Career Legacy",

        "attr.pace": "Pace",
        "attr.shooting": "Shooting",
        "attr.passing": "Passing",
        "attr.dribbling": "Dribbling",
        "attr.tackling": "Tackling",
        "attr.stamina": "Stamina",
        "attr.energy": "Energy",
        "attr.form": "Form",
        "attr.morale": "Morale",
        "attr.trust": "Manager Trust",
        "attr.fame": "Fame",
        "attr.overall": "Overall",

        "creation.title": "Create Your Player",
        "creation.subtitle": "Begin your journey from grassroots to football legend.",
        "creation.name_label": "Player Name",
        "creation.nationality_label": "Nationality",
        "creation.position_label": "Primary Position",
        "creation.foot_label": "Preferred Foot",
        "creation.foot_left": "Left",
        "creation.foot_right": "Right",
        "creation.create_button": "Confirm Profile",
        "creation.select_club_title": "Choose Your Starting Academy",
        "creation.select_club_subtitle": "Review trial contracts and select your entry club.",
        "creation.sign_contract_button": "Sign Contract",

        "tutorial.title": "Rookie Onboarding",
        "tutorial.step_counter": "Step {0} of {1}",
        "tutorial.skip_button": "Skip Tutorial",
        "tutorial.next_button": "Next",
        "tutorial.got_it_button": "Got It!",
        "tutorial.reward_title": "Starter Bonus Awarded:",
        "tutorial.reward_energy": "+{0} Energy",
        "tutorial.reward_trust": "+{0} Manager Trust",
        "tutorial.reward_form": "+{0} Form",
        "tutorial.reward_xp": "+{0} Training XP",

        "tutorial.step.welcome.title": "Welcome to Football Life",
        "tutorial.step.welcome.desc": "Your football journey begins today. Balance your performances on the pitch with relationships, lifestyle, and media in your quest to become a legend.",
        "tutorial.step.welcome.action": "Begin Career",

        "tutorial.step.creation.title": "Define Your Identity",
        "tutorial.step.creation.desc": "Choose your player's name, nationality, primary position, and preferred foot. Your position shapes your natural attributes and match responsibilities.",
        "tutorial.step.creation.action": "Configure Player",

        "tutorial.step.signing.title": "Sign Your First Contract",
        "tutorial.step.signing.desc": "Several clubs are offering you an academy trial. Review the squad status, weekly wage, and manager trust before putting pen to paper.",
        "tutorial.step.signing.action": "Review Offers",

        "tutorial.step.training.title": "Sharpen Your Skills",
        "tutorial.step.training.desc": "Hit the training pitch to boost your abilities. High training intensity accelerates growth but consumes energy. Keep an eye on fatigue!",
        "tutorial.step.training.action": "Start First Session",

        "tutorial.step.debut.title": "Your Match Debut",
        "tutorial.step.debut.desc": "Matchday has arrived! When your opportunity strikes in the match engine, swipe to aim your passes and strikes with precision.",
        "tutorial.step.debut.action": "Enter Match",

        "tutorial.step.apartment.title": "Home Life & Recovery",
        "tutorial.step.apartment.desc": "Football is only half the battle. Return to your apartment to rest, recover energy, and upgrade your living environment as your wages grow.",
        "tutorial.step.apartment.action": "Visit Apartment",

        "tutorial.step.phone.title": "Your Smartphone & Contacts",
        "tutorial.step.phone.desc": "Check your phone for messages from teammates, manager feedback, transfer rumors, and social opportunities that shape your reputation.",
        "tutorial.step.phone.action": "Check Smartphone",

        "tutorial.step.completed.title": "You're Ready for the Big Leagues!",
        "tutorial.step.completed.desc": "You have mastered the fundamentals of Football Life. The entire footballing world is now at your feet. Train hard, play passionately, and leave your legacy!",
        "tutorial.step.completed.action": "Start Playing",

        "language.select_title": "Select Language",
        "language.current": "Language: {0}"
    },
    "es": {
        "common.confirm": "Confirmar",
        "common.cancel": "Cancelar",
        "common.back": "Atrás",
        "common.continue": "Continuar",
        "common.close": "Cerrar",
        "common.save": "Guardar",
        "common.loading": "Cargando...",
        "common.skip": "Omitir",
        "common.next": "Siguiente",
        "common.finish": "Finalizar",
        "common.level": "Nivel",
        "common.week": "Semana",
        "common.season": "Temporada",
        "common.currency": "€",

        "nav.hub": "Centro de Carrera",
        "nav.overview": "Resumen",
        "nav.match": "Jugar Partido",
        "nav.training": "Entrenamiento",
        "nav.rest": "Descanso y Recuperación",
        "nav.shop": "Tienda de Estilo",
        "nav.social": "Actividades Sociales",
        "nav.events": "Eventos de Vida",
        "nav.phone": "Teléfono",
        "nav.transfers": "Mercado de Fichajes",
        "nav.sponsorship": "Patrocinios",
        "nav.legacy": "Legado de Carrera",

        "attr.pace": "Ritmo",
        "attr.shooting": "Tiro",
        "attr.passing": "Pase",
        "attr.dribbling": "Regate",
        "attr.tackling": "Entrada",
        "attr.stamina": "Resistencia",
        "attr.energy": "Energía",
        "attr.form": "Forma",
        "attr.morale": "Moral",
        "attr.trust": "Confianza del Míster",
        "attr.fame": "Fama",
        "attr.overall": "Media",

        "creation.title": "Crea Tu Jugador",
        "creation.subtitle": "Comienza tu viaje desde las categorías inferiores hasta leyenda del fútbol.",
        "creation.name_label": "Nombre del Jugador",
        "creation.nationality_label": "Nacionalidad",
        "creation.position_label": "Posición Principal",
        "creation.foot_label": "Pie Preferido",
        "creation.foot_left": "Izquierdo",
        "creation.foot_right": "Derecho",
        "creation.create_button": "Confirmar Perfil",
        "creation.select_club_title": "Elige Tu Cantera de Inicio",
        "creation.select_club_subtitle": "Revisa las ofertas de prueba y elige tu club de inicio.",
        "creation.sign_contract_button": "Firmar Contrato",

        "tutorial.title": "Bienvenida para Novatos",
        "tutorial.step_counter": "Paso {0} de {1}",
        "tutorial.skip_button": "Omitir Tutorial",
        "tutorial.next_button": "Siguiente",
        "tutorial.got_it_button": "¡Entendido!",
        "tutorial.reward_title": "Bonificación Inicial Otorgada:",
        "tutorial.reward_energy": "+{0} Energía",
        "tutorial.reward_trust": "+{0} Confianza del Míster",
        "tutorial.reward_form": "+{0} Forma",
        "tutorial.reward_xp": "+{0} XP de Entrenamiento",

        "tutorial.step.welcome.title": "Bienvenido a Football Life",
        "tutorial.step.welcome.desc": "Tu carrera futbolística comienza hoy. Equilibra tus actuaciones en el campo con tus relaciones, estilo de vida y prensa en tu camino a ser leyenda.",
        "tutorial.step.welcome.action": "Comenzar Carrera",

        "tutorial.step.creation.title": "Define Tu Identidad",
        "tutorial.step.creation.desc": "Elige el nombre de tu jugador, nacionalidad, posición y pie preferido. Tu posición moldeará tus atributos naturales y responsabilidades.",
        "tutorial.step.creation.action": "Configurar Jugador",

        "tutorial.step.signing.title": "Firma Tu Primer Contrato",
        "tutorial.step.signing.desc": "Varios clubes te ofrecen una prueba. Revisa el rol en la plantilla, salario semanal y confianza del entrenador antes de estampar la firma.",
        "tutorial.step.signing.action": "Revisar Ofertas",

        "tutorial.step.training.title": "Mejora Tus Habilidades",
        "tutorial.step.training.desc": "Salta al campo de entrenamiento para mejorar tus atributos. La alta intensidad acelera el crecimiento pero gasta energía. ¡Cuidado con la fatiga!",
        "tutorial.step.training.action": "Primera Sesión",

        "tutorial.step.debut.title": "Tu Debut en Partido",
        "tutorial.step.debut.desc": "¡Llegó el día del partido! Cuando surja tu oportunidad en el motor de juego, desliza para apuntar tus pases y disparos con precisión.",
        "tutorial.step.debut.action": "Jugar Partido",

        "tutorial.step.apartment.title": "Vida en Casa y Descanso",
        "tutorial.step.apartment.desc": "El fútbol es solo la mitad de la historia. Regresa a tu apartamento para descansar, recuperar energía y mejorar tu hogar a medida que ganas dinero.",
        "tutorial.step.apartment.action": "Visitar Apartamento",

        "tutorial.step.phone.title": "Tu Móvil y Contactos",
        "tutorial.step.phone.desc": "Consulta tu teléfono para ver mensajes de compañeros, comentarios del entrenador, rumores de fichajes y oportunidades que forjan tu reputación.",
        "tutorial.step.phone.action": "Ver Teléfono",

        "tutorial.step.completed.title": "¡Listo Para las Grandes Ligas!",
        "tutorial.step.completed.desc": "Has dominado los aspectos fundamentales de Football Life. El mundo del fútbol está a tus pies. ¡Entrena duro, juega con pasión y deja tu legado!",
        "tutorial.step.completed.action": "Jugar Ahora",

        "language.select_title": "Seleccionar Idioma",
        "language.current": "Idioma: {0}"
    },
    "de": {
        "common.confirm": "Bestätigen",
        "common.cancel": "Abbrechen",
        "common.back": "Zurück",
        "common.continue": "Weiter",
        "common.close": "Schließen",
        "common.save": "Speichern",
        "common.loading": "Wird geladen...",
        "common.skip": "Überspringen",
        "common.next": "Weiter",
        "common.finish": "Fertigstellen",
        "common.level": "Stufe",
        "common.week": "Woche",
        "common.season": "Saison",
        "common.currency": "€",

        "nav.hub": "Karriere-Zentrale",
        "nav.overview": "Übersicht",
        "nav.match": "Spiel Spielen",
        "nav.training": "Training",
        "nav.rest": "Erholung",
        "nav.shop": "Lifestyle-Shop",
        "nav.social": "Freizeit",
        "nav.events": "Ereignisse",
        "nav.phone": "Smartphone",
        "nav.transfers": "Transfermarkt",
        "nav.sponsorship": "Sponsoring",
        "nav.legacy": "Karriere-Erbe",

        "attr.pace": "Tempo",
        "attr.shooting": "Schuss",
        "attr.passing": "Passen",
        "attr.dribbling": "Dribbling",
        "attr.tackling": "Zweikampf",
        "attr.stamina": "Ausdauer",
        "attr.energy": "Energie",
        "attr.form": "Form",
        "attr.morale": "Moral",
        "attr.trust": "Trainervertrauen",
        "attr.fame": "Bekanntheit",
        "attr.overall": "Gesamt",

        "creation.title": "Erstelle Deinen Spieler",
        "creation.subtitle": "Starte deinen Weg von den Amateuren zur weltweiten Fußball-Legende.",
        "creation.name_label": "Spielername",
        "creation.nationality_label": "Nationalität",
        "creation.position_label": "Hauptposition",
        "creation.foot_label": "Starker Fuß",
        "creation.foot_left": "Links",
        "creation.foot_right": "Rechts",
        "creation.create_button": "Profil Bestätigen",
        "creation.select_club_title": "Wähle Deine Nachwuchsakademie",
        "creation.select_club_subtitle": "Prüfe Probetrainings-Angebote und unterschreibe deinen ersten Vertrag.",
        "creation.sign_contract_button": "Vertrag Unterschreiben",

        "tutorial.title": "Neulings-Einführung",
        "tutorial.step_counter": "Schritt {0} von {1}",
        "tutorial.skip_button": "Tutorial Überspringen",
        "tutorial.next_button": "Weiter",
        "tutorial.got_it_button": "Verstanden!",
        "tutorial.reward_title": "Startbonus Erhalten:",
        "tutorial.reward_energy": "+{0} Energie",
        "tutorial.reward_trust": "+{0} Trainervertrauen",
        "tutorial.reward_form": "+{0} Form",
        "tutorial.reward_xp": "+{0} Trainings-XP",

        "tutorial.step.welcome.title": "Willkommen bei Football Life",
        "tutorial.step.welcome.desc": "Deine Karriere beginnt heute. Finde die Balance zwischen Platzleistung, Freundschaften, Lifestyle und Presse auf deinem Weg zur Legende.",
        "tutorial.step.welcome.action": "Karriere Starten",

        "tutorial.step.creation.title": "Bestimme Deine Identität",
        "tutorial.step.creation.desc": "Wähle Namen, Nationalität, Position und Fuß. Deine Position prägt deine natürlichen Attribute und deine Rolle auf dem Platz.",
        "tutorial.step.creation.action": "Spieler Gestalten",

        "tutorial.step.signing.title": "Dein Erster Profivertrag",
        "tutorial.step.signing.desc": "Mehrere Vereine bieten dir ein Probetraining an. Prüfe Kaderrolle, Gehalt und Trainervertrauen vor der Unterschrift.",
        "tutorial.step.signing.action": "Angebote Prüfen",

        "tutorial.step.training.title": "Verbessere Deine Fähigkeiten",
        "tutorial.step.training.desc": "Gehe auf den Trainingsplatz. Hohe Intensität bringt schnellen Fortschritt, kostet aber viel Energie. Achte auf Erschöpfung!",
        "tutorial.step.training.action": "Erste Einheit",

        "tutorial.step.debut.title": "Dein Erstes Pflichtspiel",
        "tutorial.step.debut.desc": "Der Spieltag ist da! Wenn sich deine Chance im Spiel ergibt, wische präzise, um Pässe und Torschüsse zu platzieren.",
        "tutorial.step.debut.action": "Zum Spiel",

        "tutorial.step.apartment.title": "Zuhause & Erholung",
        "tutorial.step.apartment.desc": "Fußball ist nur die halbe Miete. Erhole dich in deinem Apartment, schlafe gut und werte deine Wohnung mit steigendem Gehalt auf.",
        "tutorial.step.apartment.action": "Apartment Ansehen",

        "tutorial.step.phone.title": "Dein Smartphone & Kontakte",
        "tutorial.step.phone.desc": "Lies Nachrichten von Mitspielern, Feedback deines Trainers und Transfergerüchte, die dein Ansehen beeinflussen.",
        "tutorial.step.phone.action": "Smartphone Öffnen",

        "tutorial.step.completed.title": "Bereit Für Die Große Bühne!",
        "tutorial.step.completed.desc": "Du kennst jetzt alle Grundlagen von Football Life. Die ganze Fußballwelt steht dir offen. Trainiere hart und werde eine Legende!",
        "tutorial.step.completed.action": "Jetzt Starten",

        "language.select_title": "Sprache Auswählen",
        "language.current": "Sprache: {0}"
    },
    "fr": {
        "common.confirm": "Confirmer",
        "common.cancel": "Annuler",
        "common.back": "Retour",
        "common.continue": "Continuer",
        "common.close": "Fermer",
        "common.save": "Sauvegarder",
        "common.loading": "Chargement...",
        "common.skip": "Passer",
        "common.next": "Suivant",
        "common.finish": "Terminer",
        "common.level": "Niveau",
        "common.week": "Semaine",
        "common.season": "Saison",
        "common.currency": "€",

        "nav.hub": "Centre de Carrière",
        "nav.overview": "Aperçu",
        "nav.match": "Jouer le Match",
        "nav.training": "Entraînement",
        "nav.rest": "Repos & Récupération",
        "nav.shop": "Boutique Style",
        "nav.social": "Vie Sociale",
        "nav.events": "Événements de Vie",
        "nav.phone": "Smartphone",
        "nav.transfers": "Marché des Transferts",
        "nav.sponsorship": "Sponsors",
        "nav.legacy": "Héritage & Légende",

        "attr.pace": "Vitesse",
        "attr.shooting": "Tir",
        "attr.passing": "Passe",
        "attr.dribbling": "Dribble",
        "attr.tackling": "Tacle",
        "attr.stamina": "Endurance",
        "attr.energy": "Énergie",
        "attr.form": "Forme",
        "attr.morale": "Moral",
        "attr.trust": "Confiance du Coach",
        "attr.fame": "Notoriété",
        "attr.overall": "Général",

        "creation.title": "Créez Votre Joueur",
        "creation.subtitle": "Commencez votre voyage des terrains amateurs jusqu'au sommet du football mondial.",
        "creation.name_label": "Nom du Joueur",
        "creation.nationality_label": "Nationalité",
        "creation.position_label": "Poste Principal",
        "creation.foot_label": "Pied Fort",
        "creation.foot_left": "Gauche",
        "creation.foot_right": "Droit",
        "creation.create_button": "Valider le Profil",
        "creation.select_club_title": "Choisissez Votre Centre de Formation",
        "creation.select_club_subtitle": "Examinez les offres d'essai et signez dans votre premier club.",
        "creation.sign_contract_button": "Signer le Contrat",

        "tutorial.title": "Guide du Débutant",
        "tutorial.step_counter": "Étape {0} sur {1}",
        "tutorial.skip_button": "Passer le Tutoriel",
        "tutorial.next_button": "Suivant",
        "tutorial.got_it_button": "Compris !",
        "tutorial.reward_title": "Bonus de Départ Obtenu :",
        "tutorial.reward_energy": "+{0} Énergie",
        "tutorial.reward_trust": "+{0} Confiance du Coach",
        "tutorial.reward_form": "+{0} Forme",
        "tutorial.reward_xp": "+{0} XP d'Entraînement",

        "tutorial.step.welcome.title": "Bienvenue dans Football Life",
        "tutorial.step.welcome.desc": "Votre carrière débute aujourd'hui. Trouvez l'équilibre entre vos matchs, vos proches, votre vie privée et les médias pour devenir une légende.",
        "tutorial.step.welcome.action": "Commencer l'Aventure",

        "tutorial.step.creation.title": "Créez Votre Identité",
        "tutorial.step.creation.desc": "Choisissez votre nom, nationalité, poste et pied fort. Votre poste déterminera vos attributs de base et votre rôle sur le terrain.",
        "tutorial.step.creation.action": "Personnaliser le Joueur",

        "tutorial.step.signing.title": "Signez Votre Premier Contrat",
        "tutorial.step.signing.desc": "Plusieurs clubs vous proposent un essai. Comparez le temps de jeu espéré, le salaire et la confiance du coach avant de signer.",
        "tutorial.step.signing.action": "Voir les Offres",

        "tutorial.step.training.title": "Améliorez Vos Compétences",
        "tutorial.step.training.desc": "Rendez-vous à l'entraînement. Une intensité élevée favorise la progression rapide mais consomme de l'énergie. Gare à la fatigue !",
        "tutorial.step.training.action": "Première Séance",

        "tutorial.step.debut.title": "Votre Premier Match",
        "tutorial.step.debut.desc": "Le jour de match est arrivé ! Quand l'opportunité se présente, glissez votre doigt pour placer vos frappes et passes au millimètre.",
        "tutorial.step.debut.action": "Entrer sur le Terrain",

        "tutorial.step.apartment.title": "Vie Quotidienne & Repos",
        "tutorial.step.apartment.desc": "Le football n'est qu'une partie de votre vie. Rentrez chez vous pour recharger vos batteries et améliorez votre cadre de vie.",
        "tutorial.step.apartment.action": "Visiter l'Appartement",

        "tutorial.step.phone.title": "Votre Smartphone & Contacts",
        "tutorial.step.phone.desc": "Consultez vos messages de coéquipiers, les retours de l'entraîneur et les rumeurs de transfert qui façonnent votre renommée.",
        "tutorial.step.phone.action": "Ouvrir le Téléphone",

        "tutorial.step.completed.title": "Prêt pour les Sommets !",
        "tutorial.step.completed.desc": "Vous connaissez désormais les bases de Football Life. Le monde du football s'offre à vous. Donnez tout sur le terrain et écrivez l'histoire !",
        "tutorial.step.completed.action": "Jouer",

        "language.select_title": "Choisir la Langue",
        "language.current": "Langue : {0}"
    },
    "it": {
        "common.confirm": "Conferma",
        "common.cancel": "Annulla",
        "common.back": "Indietro",
        "common.continue": "Continua",
        "common.close": "Chiudi",
        "common.save": "Salva",
        "common.loading": "Caricamento...",
        "common.skip": "Salta",
        "common.next": "Avanti",
        "common.finish": "Termina",
        "common.level": "Livello",
        "common.week": "Settimana",
        "common.season": "Stagione",
        "common.currency": "€",

        "nav.hub": "Centro Carriera",
        "nav.overview": "Panoramica",
        "nav.match": "Gioca Partita",
        "nav.training": "Allenamento",
        "nav.rest": "Riposo & Recupero",
        "nav.shop": "Negozio Stile",
        "nav.social": "Vita Sociale",
        "nav.events": "Eventi di Vita",
        "nav.phone": "Smartphone",
        "nav.transfers": "Calciomercato",
        "nav.sponsorship": "Sponsorizzazioni",
        "nav.legacy": "Eredità di Carriera",

        "attr.pace": "Velocità",
        "attr.shooting": "Tiro",
        "attr.passing": "Passaggio",
        "attr.dribbling": "Dribbling",
        "attr.tackling": "Contrasto",
        "attr.stamina": "Resistenza",
        "attr.energy": "Energia",
        "attr.form": "Forma",
        "attr.morale": "Morale",
        "attr.trust": "Fiducia del Mister",
        "attr.fame": "Fama",
        "attr.overall": "Generale",

        "creation.title": "Crea il Tuo Calciatore",
        "creation.subtitle": "Inizia la tua scalata dai campi giovanili alla gloria del calcio mondiale.",
        "creation.name_label": "Nome Giocatore",
        "creation.nationality_label": "Nazionalità",
        "creation.position_label": "Ruolo Principale",
        "creation.foot_label": "Piede Preferito",
        "creation.foot_left": "Sinistro",
        "creation.foot_right": "Destro",
        "creation.create_button": "Conferma Profilo",
        "creation.select_club_title": "Scegli la Tua Squadra Giovanile",
        "creation.select_club_subtitle": "Esamina le offerte di prova e firma il tuo primo contratto.",
        "creation.sign_contract_button": "Firma Contratto",

        "tutorial.title": "Guida per Esordienti",
        "tutorial.step_counter": "Passo {0} di {1}",
        "tutorial.skip_button": "Salta Tutorial",
        "tutorial.next_button": "Avanti",
        "tutorial.got_it_button": "Ho Capito!",
        "tutorial.reward_title": "Bonus di Benvenuto Assegnato:",
        "tutorial.reward_energy": "+{0} Energia",
        "tutorial.reward_trust": "+{0} Fiducia del Mister",
        "tutorial.reward_form": "+{0} Forma",
        "tutorial.reward_xp": "+{0} XP Allenamento",

        "tutorial.step.welcome.title": "Benvenuto in Football Life",
        "tutorial.step.welcome.desc": "La tua avventura calcistica comincia oggi. Bilancia le prestazioni sul campo con le relazioni personali, lo stile di vita e i media per diventare una leggenda.",
        "tutorial.step.welcome.action": "Inizia Carriera",

        "tutorial.step.creation.title": "Definisci la Tua Identità",
        "tutorial.step.creation.desc": "Scegli nome, nazionalità, ruolo e piede preferito. Il ruolo determinerà le tue caratteristiche e compiti tattici.",
        "tutorial.step.creation.action": "Configura Calciatore",

        "tutorial.step.signing.title": "Firma il Tuo Primo Contratto",
        "tutorial.step.signing.desc": "Diversi club ti offrono un provino. Valuta il ruolo in squadra, lo stipendio settimanale e la fiducia del mister prima di firmare.",
        "tutorial.step.signing.action": "Esamina Offerte",

        "tutorial.step.training.title": "Migliora le Tue Qualità",
        "tutorial.step.training.desc": "Scendi in campo per allenarti. Un'intensità alta accelera la crescita ma consuma energia. Fai attenzione alla fatica!",
        "tutorial.step.training.action": "Prima Seduta",

        "tutorial.step.debut.title": "Il Tuo Debutto in Partita",
        "tutorial.step.debut.desc": "È arrivato il giorno della partita! Quando scatta l'azione, scorri con il dito per piazzare passaggi e tiri precisi.",
        "tutorial.step.debut.action": "Entra in Campo",

        "tutorial.step.apartment.title": "Casa & Recupero",
        "tutorial.step.apartment.desc": "Il campo è solo una parte della tua vita. Torna nel tuo appartamento per riposare, recuperare energia e migliorare la tua casa con i tuoi guadagni.",
        "tutorial.step.apartment.action": "Visita Appartamento",

        "tutorial.step.phone.title": "Il Tuo Smartphone & Contatti",
        "tutorial.step.phone.desc": "Controlla i messaggi dei compagni, le opinioni del mister e le voci di mercato che influenzano la tua popolarità.",
        "tutorial.step.phone.action": "Apri Smartphone",

        "tutorial.step.completed.title": "Pronto per la Grande Ribalta!",
        "tutorial.step.completed.desc": "Hai appreso tutte le basi di Football Life. Il mondo del calcio è ai tuoi piedi. Allenati duramente, gioca con passione e crea la tua leggenda!",
        "tutorial.step.completed.action": "Inizia a Giocare",

        "language.select_title": "Seleziona Lingua",
        "language.current": "Lingua: {0}"
    }
}

os.makedirs("content/data/localization", exist_ok=True)
for lang, catalog in locales.items():
    path = f"content/data/localization/{lang}.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(catalog, f, ensure_ascii=False, indent=2)
    print(f"Wrote {len(catalog)} strings to {path}")

# Verify parity
en_keys = set(locales["en"].keys())
for lang, catalog in locales.items():
    if lang == "en": continue
    curr_keys = set(catalog.keys())
    missing = en_keys - curr_keys
    extra = curr_keys - en_keys
    if missing:
        print(f"Error: {lang} is missing {len(missing)} keys: {missing}")
    if extra:
        print(f"Warning: {lang} has {len(extra)} extra keys: {extra}")
    assert missing == set(), f"Missing keys in {lang}"

print("All localization catalogs verified with 100% key parity!")
